# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build BestEats/ --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'

  - script: dotnet test BestEats.Tests/
    displayName: 'Unit Test'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Azure subscription 1(54aeee99-cfaf-4de7-9c10-a360891a5e01)'
      appType: 'webApp'
      WebAppName: 'https://besteats/.azurewebsites.net/'
      packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
